const express=require('express')
const router=express.Router()
const{cancelOrder,getOrders,postOrders,getProduct,getProducts,log,sign,forget,reset,resetok}=require('./controller')
router.post('/signup',sign)
router.post('/login',log)
router.post('/forgetpass',forget)
router.get('/reset/:id/:token',reset)
router.post('/reset/:id/:token',resetok)
router.get('/products',getProducts)
router.get('/products/:id',getProduct)
router.post('/orders',postOrders)
router.get('/orders/:id',getOrders)
router.post('/cancel/:id',cancelOrder)
module.exports=router